on:
  push:
    branches: [master]
jobs:
  build:
    name: Check and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Build Images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: |
            python_test:latest
