on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Check and Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install alembic
          alembic init alembic
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Build Images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: |
            python_test:latest
      - name: Start a test PostgreSQL database server
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          service: db_test
          exit-code: 0
          options: >-
            --detach
            --env POSTGRES_USER=DB_user
            --env POSTGRES_PASSWORD=DB_password
            --env POSTGRES_DB=project
            --env DB_HOST=localhost
            --env DB_PORT=5432
      - name: Stop PostgreSQL database servers
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          command: down
          remove-volumes: true

      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: niksgont/server-sna

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: connect to server and deploy the application
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker pull niksgont/server-sna:master
            docker run -d --name nastya-python -e DB_USER=${{ secrets.DB_USER }} -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} -e DB_URL=${{ secrets.DB_URL }} -e REQUEST_URL='159.89.215.206:8000' -p 8012:8000 nastya:1
            cd ${{ secrets.WORK_DIR }}
            git checkout ${{ secrets.MAIN_BRANCH }}
            git pull
            echo "Deploy successful"
